name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v6
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.rustup
            target
          key: ${{ runner.os }}-${{ runner.arch }}
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --all --check
      - run: cargo rustdoc -p=freertos-next -- -D warnings
      - name: Build
        run: cargo build --verbose

  examples:
    strategy:
      matrix:
        include:
          - example: win
            target: x86_64-pc-windows-msvc
            os: windows-latest
          - example: linux
            target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - example: stm32-cortex-m3
            target: thumbv7m-none-eabi
            os: ubuntu-latest
          - example: stm32-cortex-m4-blackpill
            target: thumbv7em-none-eabihf
            os: ubuntu-latest
          - example: nrf9160
            target: thumbv8m.main-none-eabihf
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    #env:
    #  RUSTFLAGS: -D warnings # Warnings disabled only in CI
    steps:
      - name: Clone
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.rustup
            target
          key: ${{ runner.os }}-${{ runner.arch }}
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Install cross deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          case ${{ matrix.target }} in
            "x86_64-pc-windows-gnu")
              sudo apt-get install -y gcc-mingw-w64
              ;;
            "thumbv7m-none-eabi" | "thumbv7em-none-eabihf" | "thumbv8m.main-none-eabihf")
              sudo apt-get install -y gcc-arm-none-eabi
              ;;
          esac
      - name: Build example
        run: cargo build --verbose --example ${{ matrix.example }} --target ${{ matrix.target }}
